# FortiShield App Copyright (C) 2017, FortiShield Inc. (License GPLv2)
version: '3.7'

services:
  fortishield.manager:
    build:
      context: fortishield-manager/
      args:
        FORTISHIELD_VERSION: ${FORTISHIELD_VERSION}
        FORTISHIELD_TAG_REVISION: ${FORTISHIELD_TAG_REVISION}
        FILEBEAT_TEMPLATE_BRANCH: ${FILEBEAT_TEMPLATE_BRANCH}
        FORTISHIELD_FILEBEAT_MODULE: ${FORTISHIELD_FILEBEAT_MODULE}
    image: fortishield/fortishield-manager:${FORTISHIELD_IMAGE_VERSION}
    hostname: fortishield.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://fortishield.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=none
    volumes:
      - fortishield_api_configuration:/var/ossec/api/configuration
      - fortishield_etc:/var/ossec/etc
      - fortishield_logs:/var/ossec/logs
      - fortishield_queue:/var/ossec/queue
      - fortishield_var_multigroups:/var/ossec/var/multigroups
      - fortishield_integrations:/var/ossec/integrations
      - fortishield_active_response:/var/ossec/active-response/bin
      - fortishield_agentless:/var/ossec/agentless
      - fortishield_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat

  fortishield.indexer:
    build:
      context: fortishield-indexer/
      args:
        FORTISHIELD_VERSION: ${FORTISHIELD_VERSION}
        FORTISHIELD_TAG_REVISION: ${FORTISHIELD_TAG_REVISION}
    image: fortishield/fortishield-indexer:${FORTISHIELD_IMAGE_VERSION}
    hostname: fortishield.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  fortishield.dashboard:
    build:
      context: fortishield-dashboard/
      args:
        FORTISHIELD_VERSION: ${FORTISHIELD_VERSION}
        FORTISHIELD_TAG_REVISION: ${FORTISHIELD_TAG_REVISION}
        FORTISHIELD_UI_REVISION: ${FORTISHIELD_UI_REVISION}
    image: fortishield/fortishield-dashboard:${FORTISHIELD_IMAGE_VERSION}
    hostname: fortishield.dashboard
    restart: always
    ports:
      - 443:443
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - SERVER_SSL_ENABLED=false
      - FORTISHIELD_API_URL=https://fortishield.manager
    depends_on:
      - fortishield.indexer
    links:
      - fortishield.indexer:fortishield.indexer
      - fortishield.manager:fortishield.manager

volumes:
  fortishield_api_configuration:
  fortishield_etc:
  fortishield_logs:
  fortishield_queue:
  fortishield_var_multigroups:
  fortishield_integrations:
  fortishield_active_response:
  fortishield_agentless:
  fortishield_wodles:
  filebeat_etc:
  filebeat_var:
