# FortiShield App Copyright (C) 2017, FortiShield Inc. (License GPLv2)
version: '3.7'

services:
  fortishield.manager:
    image: fortishield/fortishield-manager:5.0.0
    hostname: fortishield.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://fortishield.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=fortishield-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - fortishield_api_configuration:/var/ossec/api/configuration
      - fortishield_etc:/var/ossec/etc
      - fortishield_logs:/var/ossec/logs
      - fortishield_queue:/var/ossec/queue
      - fortishield_var_multigroups:/var/ossec/var/multigroups
      - fortishield_integrations:/var/ossec/integrations
      - fortishield_active_response:/var/ossec/active-response/bin
      - fortishield_agentless:/var/ossec/agentless
      - fortishield_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/fortishield_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/fortishield_indexer_ssl_certs/fortishield.manager.pem:/etc/ssl/filebeat.pem
      - ./config/fortishield_indexer_ssl_certs/fortishield.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/fortishield_cluster/fortishield_manager.conf:/fortishield-config-mount/etc/ossec.conf

  fortishield.indexer:
    image: fortishield/fortishield-indexer:5.0.0
    hostname: fortishield.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - 'INDEXER_PASSWORD=SecretPassword'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - fortishield-indexer-data:/var/lib/fortishield-indexer
      - ./config/fortishield_indexer_ssl_certs/root-ca.pem:/usr/share/fortishield-indexer/certs/root-ca.pem
      - ./config/fortishield_indexer_ssl_certs/fortishield.indexer-key.pem:/usr/share/fortishield-indexer/certs/fortishield.indexer.key
      - ./config/fortishield_indexer_ssl_certs/fortishield.indexer.pem:/usr/share/fortishield-indexer/certs/fortishield.indexer.pem
      - ./config/fortishield_indexer_ssl_certs/admin.pem:/usr/share/fortishield-indexer/certs/admin.pem
      - ./config/fortishield_indexer_ssl_certs/admin-key.pem:/usr/share/fortishield-indexer/certs/admin-key.pem
      - ./config/fortishield_indexer/fortishield.indexer.yml:/usr/share/fortishield-indexer/opensearch.yml
      - ./config/fortishield_indexer/internal_users.yml:/usr/share/fortishield-indexer/opensearch-security/internal_users.yml

  fortishield.dashboard:
    image: fortishield/fortishield-dashboard:5.0.0
    hostname: fortishield.dashboard
    restart: always
    ports:
      - 443:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FORTISHIELD_API_URL=https://fortishield.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=fortishield-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - ./config/fortishield_indexer_ssl_certs/fortishield.dashboard.pem:/usr/share/fortishield-dashboard/certs/fortishield-dashboard.pem
      - ./config/fortishield_indexer_ssl_certs/fortishield.dashboard-key.pem:/usr/share/fortishield-dashboard/certs/fortishield-dashboard-key.pem
      - ./config/fortishield_indexer_ssl_certs/root-ca.pem:/usr/share/fortishield-dashboard/certs/root-ca.pem
      - ./config/fortishield_dashboard/opensearch_dashboards.yml:/usr/share/fortishield-dashboard/config/opensearch_dashboards.yml
      - ./config/fortishield_dashboard/fortishield.yml:/usr/share/fortishield-dashboard/data/fortishield/config/fortishield.yml
      - fortishield-dashboard-config:/usr/share/fortishield-dashboard/data/fortishield/config
      - fortishield-dashboard-custom:/usr/share/fortishield-dashboard/plugins/fortishield/public/assets/custom
    depends_on:
      - fortishield.indexer
    links:
      - fortishield.indexer:fortishield.indexer
      - fortishield.manager:fortishield.manager

volumes:
  fortishield_api_configuration:
  fortishield_etc:
  fortishield_logs:
  fortishield_queue:
  fortishield_var_multigroups:
  fortishield_integrations:
  fortishield_active_response:
  fortishield_agentless:
  fortishield_wodles:
  filebeat_etc:
  filebeat_var:
  fortishield-indexer-data:
  fortishield-dashboard-config:
  fortishield-dashboard-custom:
